-- MySQL Script generated by MySQL Workbench
-- Fri Jun  9 02:47:30 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sorteio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sorteio` ;

-- -----------------------------------------------------
-- Schema sorteio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sorteio` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `sorteio` ;

-- -----------------------------------------------------
-- Table `ponto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ponto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `ponto` (
  `idponto` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idponto`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
